#!/usr/bin/env zsh
killall -q swayidle waybar dunst # Kill old proccess, so it will not overlaping process

# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                    Audio                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
(( $+commands[pipewire] )) && [[ -z "$(pidof pipewire)" ]] && pipewire &!                   # Check command if it available && check if process program not running && start pipewire
(( $+commands[pipewire-pulse] )) && [[ -z "$(pidof pipewire-pulse)" ]] && pipewire-pulse &! # Check command if it available && check if process program not running && start pipewire-pulse
(( $+commands[wireplumber] )) && [[ -z "$(pidof wireplumber)" ]] && wireplumber &!          # Check command if it available && check if process program not running && start wireplumber
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                  Wallpaper                                   │
# ╰──────────────────────────────────────────────────────────────────────────────╯
(( $+functions[wallpaper-handler] )) && wallpaper-handler &! # Check function if it available && Call wallpaper-handler to set wallpaper
# (( $+functions[live-wallpaper-handler] )) && live-wallpaper-handler nolooptop /opt/craccken/live-wallpaper/craccken-live-wallpaper.mp4 # Check function if it available && run live-wallpaper :D
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                Screencasting                                 │
# ╰──────────────────────────────────────────────────────────────────────────────╯
[[ -f /usr/lib/xdg-desktop-portal ]] && /usr/lib/xdg-desktop-portal -r &!
[[ -f /usr/lib/xdg-desktop-portal-wlr ]] && /usr/lib/xdg-desktop-portal-wlr -r &!
[[ -f /usr/lib/xdg-desktop-portal-gtk ]] && /usr/lib/xdg-desktop-portal-gtk -r &!
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                  Statusbar                                   │
# ╰──────────────────────────────────────────────────────────────────────────────╯
# (( $+commands[waybar] )) && waybar -c /etc/xdg/waybar/vertical-bar_config -s /etc/xdg/waybar/bar.css &! # Check command if it available && start waybar
(( $+commands[waybar] )) && waybar -c /etc/xdg/waybar/horizontal-bar_config -s /etc/xdg/waybar/bar.css &! # Check command if it available && start waybar
(( $+commands[eww] )) && eww --restart open statusbar
generate-workspaces-component &!
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                    Music                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
(( $+commands[mpd] )) && mpd &!
(( $+commands[mpDris2] )) && mpDris2 &!
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                 Notification                                 │
# ╰──────────────────────────────────────────────────────────────────────────────╯
(( $+commands[dunst] )) && dunst &! # Check command if it available && start notification-daemon
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                  Brightness                                  │
# ╰──────────────────────────────────────────────────────────────────────────────╯
BrightnessHandler set_minimum_brightness 5 &! # set minimum capacity of brightness
# (( $+functions[this-will-save-your-eyes] )) && this-will-save-your-eyes &! # Check function if it available && start wlsunset
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                    Other                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
(( $+commands[activate-linux] )) && [[ -z "$(pidof activate-linux)" ]] && activate-linux &! # Check if there is no process of command && Start activate-linux
(( $+commands[swayidle] )) && swayidle -w timeout 300 '/bin/zsh -ic "lock-screen"' timeout 600 '/bin/zsh -ic "BrightnessHandler save_current_brightness && BrightnessHandler set_value 7"' resume '/bin/zsh -ic "BrightnessHandler restore_brightness"' &! # Check command if it available && start idle manager
autoload active-window-flickers-border && active-window-flickers-border &!
