#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn

echo "" # Print string
elapsed-time-execution-command # Call command
RPROMPT="%F{#36a3d9}%K{#030d11}  ${elapsed_time_execution:-} %K{reset}%F{reset}" # Set right-prompt style
