#!/bin/env zsh
# vim:ft=sh
#  ███████╗███████╗██╗  ██╗        ██╗      ██████╗  ██████╗  ██████╗ ██╗   ██╗████████╗
#  ╚══███╔╝██╔════╝██║  ██║        ██║     ██╔═══██╗██╔════╝ ██╔═══██╗██║   ██║╚══██╔══╝
#    ███╔╝ ███████╗███████║        ██║     ██║   ██║██║  ███╗██║   ██║██║   ██║   ██║   
#   ███╔╝  ╚════██║██╔══██║        ██║     ██║   ██║██║   ██║██║   ██║██║   ██║   ██║   
#  ███████╗███████║██║  ██║███████╗███████╗╚██████╔╝╚██████╔╝╚██████╔╝╚██████╔╝   ██║   
#  ╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝  ╚═════╝  ╚═════╝  ╚═════╝    ╚═╝   
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │           /etc/zsh/zlogout: system-wide .zlogout file for zsh(1).            │
# ╰──────────────────────────────────────────────────────────────────────────────╯
# ▲
# █  When a login shell exit this file will be executed, this happens with       
# █  exit via exit or logout commands.                                           
# █  However, if the shell terminates due to executing another process this      
# █  files will not be executed.                                                 
# ▼                                                                               
#[[ $EUID -eq 0 ]] && clear_cache &>/dev/null # Check if root-user && execute file that will clear cache
