#!/bin/env zsh
# vim:ft=sh
#  ███████╗███████╗██╗  ██╗        ██████╗ ██████╗  ██████╗ ███████╗██╗██╗     ███████╗
#  ╚══███╔╝██╔════╝██║  ██║        ██╔══██╗██╔══██╗██╔═══██╗██╔════╝██║██║     ██╔════╝
#    ███╔╝ ███████╗███████║        ██████╔╝██████╔╝██║   ██║█████╗  ██║██║     █████╗  
#   ███╔╝  ╚════██║██╔══██║        ██╔═══╝ ██╔══██╗██║   ██║██╔══╝  ██║██║     ██╔══╝  
#  ███████╗███████║██║  ██║███████╗██║     ██║  ██║╚██████╔╝██║     ██║███████╗███████╗
#  ╚══════╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │          /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).           │
# ╰──────────────────────────────────────────────────────────────────────────────╯
# ▲
# █  This file is sourced only for login shells (i.e. shells                     
# █  invoked with "-" as the first character of argv[0], and                     
# █  shells invoked with the -l flag.)                                           
# █  Global Order: zshenv, zprofile, zshrc, zlogin                               
# ▼                                                                               
emulate sh -c 'source /etc/profile' # Source global initialization script, don't remove this line!!!
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                     Source file in /etc/zsh/zprofile.d/                      │
# ╰──────────────────────────────────────────────────────────────────────────────╯
[[ -d "/etc/zsh/zprofile.d" ]] && { # Check if has /etc/zsh/zprofile.d directory && execute function below
    for file in /etc/zsh/zprofile.d/*(.); do # Create for-loop with file in /etc/zsh/zprofile.d/ directory
        eval "$(<${file})" # Check if file is readable && source the file
    done; unset file # End for-loop statement; Clearing variable so that will not polute the shell.
}
