#!/usr/bin/env bash
sudo pacman -Sy --noconfirm archlinux-keyring
sudo pacman -Sy --needed --noconfirm archiso mkinitcpio-archiso

[[ -d ./work ]] && sudo rm -rf ./work # Clean work-directory
[[ -d ./output ]] && sudo mv ./output/* ../ || : # Clean output-directory

sudo mkarchiso -v -o ./output ./prefix 2>./.error.log # Start mkarchiso
# sudo umount ./work/x86_64/airootfs/dev
