#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed sudo # Check if command is installed

if (( $+commands[doas] )); then # Check if doas is available
    /usr/bin/doas sleep 0.0001 # Ask password for sleep command with doas
    return $? # Exit
fi # End if-else statement

ask_msg "Enter your password!"; local password; read -s password # Ask password
echo "${password}" | /usr/bin/sudo -S sleep 0.0001 # Input password variable to sudo
return $? # Exit
