#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset
need_installed sudo || return $? # Check if command is installed || exit with error exit-code

if [[ ! -f "/usr/bin/doas" ]]; then # Check if doas not available
    ask_msg "Enter your password!"; local password; read -s password # Ask password
    echo "${password}" | /usr/bin/sudo -S sleep 0.0001 # Input password variable to sudo
    return $? # Exit
fi # End if-else statement
/usr/bin/doas sleep 0.0001
return $? # Exit
