#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed ip grep cut # Check if command is installed : exit

ip route show | grep default | cut -d ' ' -f 3 # Get gateway information from ip command
