#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed hyprctl jq # Need installed in order to run

hyprctl workspaces -j | jq -r '.[].id' # Get list of used workspace id number
