#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail

if [[ ! "$TERMINAL_WIDTH" == "$(tput cols)" ]]; then # Check if terminal width is not same as width size
    export TERMINAL_WIDTH="$(tput cols)" # Set new terminal width with new value
    return # Return good
fi # End if-else statement
return 1 # Return error exit-code
