#!/usr/bin/env zsh
#          ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#          ┃       Select window on current workspace with select-region-on-screen        ┃
#          ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed hyprctl # Need installed in order to run

hyprctl clients -j | jq -r ".[] | select(.workspace.id == $(get-current-workspace-id))" | jq -r ".at,.size" | jq -s "add" | jq '_nwise(4)' | jq -r '"\(.[0]),\(.[1]) \(.[2])x\(.[3])"' | select-region-on-screen
