#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn

[[ -n "${1:-}" ]] && { # Check if argument-1 is not empty && execute this below
    # ╭──────────────────────────────────────────────────────────────────────────────╮
    # │           See `errno -l` if you want errno names and descriptions            │
    # ╰──────────────────────────────────────────────────────────────────────────────╯
    local EXIT_CODE ERRNO_NAME ERRNO_DESCRIPTION # Declare empty variable
    read -r ERRNO_NAME EXIT_CODE ERRNO_DESCRIPTION <<<$(errno $1) # Asign multiple variable
    error_msg "$ERRNO_NAME : $ERRNO_DESCRIPTION"
    return $EXIT_CODE
}
