#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal; set -o pipefail

(>&2 print -P "\n%F{#d4d104}%K{#232201}  %* %D{%d-%m-%Y} ┆ $1 %F{#232201}%K{reset}%F{reset}") # Perform prompt expansion (see EXPANSION OF PROMPT SEQUENCES in zshmisc(1)).
