#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset

tput blink # Start blinking text
(>&2 print -P "\n%F{#d4d104}%K{#232201}  %* %D{%d-%m-%Y} ┆ ${1:-} %F{#232201}%K{reset}%F{reset}") # Perform prompt expansion (see EXPANSION OF PROMPT SEQUENCES in zshmisc(1)).
tput sgr0 # Turn off all attributes
