#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed scdl # Check if command is installed
need_internet # Check if there is available connection
must_have_argument ${1:-} # Must have argument-1 passed to this function

scdl --force-metadata --overwrite --addtimestamp --flac --original-name --original-art --hide-progress --extract-artist -l "$1"
