#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal; set -o pipefail
need_installed pwgen || return $? # Check if command is installed || exit

{pwgen -s -y -n -c -1 "${1:-77}" | wl-copy;} && notify-send -u critical "Password Generator" "Random password coppied to the clipboard!" # Generate random password and notify it & copy to clipboard 
