#!/usr/bin/env zsh
# vim:ft=sh
#          ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#          ┃                 Open up random file in random line on editor                 ┃
#          ┃                       it will make you look busier :D                        ┃
#          ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed find wc cut shuf nvim # Check if command is installed

local random_file=$(find /usr/include -type f | shuf -n 1) # Pick random file from /usr/include
local file_lengths=$(wc -l "${random_file}" | cut -d ' ' -f 1) # Get line counts from random_file
local random_line=$(( RANDOM % file_lengths )) # Pick random line from file_lengths
nvim +${random_line} "${random_file}" # Open up random_file in random_line on neovim
