#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed pacman xdg-open grep # Check if command is installed
must_have_argument ${1:-} # Must have argument-1 passed || exit 

local info_package="$(/usr/bin/pacman -Si "${1}")" # Get info-package from pacman
local architecture="$(/usr/bin/grep -m 1 '^Arch' <<< "${info_package}" | tr -d ' ' | cut -d ':' -f 2)" # Grab information about architecture of the package
local repository="$(/usr/bin/grep -m 1 '^Repo' <<< "${info_package}" | tr -d ' ' | cut -d ':' -f 2)" # Grab information about repository that package placed
[[ -n "${info_package:-}" ]] && xdg-open "https://www.archlinux.org/packages/$repository/$architecture/${1}/" &>/dev/null # Open in browset
