---
outputMode: active
scale: 1
background:
  red: 0.0
  green: 0.0
  blue: 0.0
  opacity: 0.8999999761581421
widget:
  margin:
    margins:
      - 20
      - 20
      - 20
      - 20
    widget:
      verticalLayout:
        - horizontalLayout:
            - margin:
                margins:
                  - 0
                  - 88
                  - 0
                  - 32
                widget:
                  verticalLayout:
                    - date:
                        font: ~
                        font_size: 64.0
                    - clock:
                        font: ~
                        font_size: 256.0
            - verticalLayout:
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      battery:
                        font: ~
                        font_size: 24.0
                        length: 0
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      backlight:
                        device: intel_backlight
                        font: ~
                        font_size: 24.0
                        length: 0
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 0
                    widget:
                      pulseAudio:
                        font: monoa
                        font_size: 40
                        length: 0
        - calendar:
            font_primary: mono
            font_secondary: sans
            font_size: 16.0
            sections: 3
        - launcher:
            font: sans 
            font_size: 32.0
            length: 0
            app_opener: "riverctl spawn"
            term_opener: "st --"
            url_opener: "xdg-open"
fonts:
  sans: "CozetteVector"
  mono: "Alkhemikal"
  monoa: "OwreKynge"
