#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed wofi ps sed kill awk # Check if command is installed

ps -Af | sed 1d | wofi --show=dmenu -i "$@" | awk '{print $2}' | xargs kill -${1:-9} # List all process id and pick it with wofi then kill it
