#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed socat # Need install this in order to run

get-number-clients-current-workspace # Get initial value
local event event_data event_name # Create variable for storing event from hyprland
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read event; do # Create while-loop for read event from hyprland socket
    read -r event_name event_data <<<$(echo ${event} | sed 's/>>/ /g') # Get event name and data from hyprland socket event & store it into variable
    [[ "${event_name}" == "openwindow" || "${event_name}" == "closewindow" || "${event_name}" == "workspace" ]] && get-number-clients-current-workspace # Call functions for every specified event
done # End while-loop statement
