#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed hyprctl jq # Need installed in order to run

hyprctl activewindow -j | jq -Mc -r '.at | "\(.[0]),\(.[1])"' # Get current window size, heightxwidth
