#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed hyprctl jq # Need installed in order to run

hyprctl activewindow -j | jq -Mc -r '.size | "\(.[0])x\(.[1])"' # Get current window size, heightxwidth
