#!/usr/bin/env zsh 
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed swaylock grim paplay # Check if command installed
need_normal_user # Need normal user to run
autoload edit-image-glitch resize-image # Load functions

killall -q swaylock grim paplay || : # Clean up old process
local temporary_file="/tmp/lockscreen-bg-$$.png" # Create local variable for storing temporary_file name
grim "$temporary_file" # Screenshot the whole screen and then output into temporary_file
resize-image "$temporary_file" "$temporary_file" '20%' # Resize the output of screenshot, this will make blurry low resolution image
edit-image-glitch "$temporary_file" "$temporary_file" & # Edit the output of screenshot with glitch effect and then output it into temporary_file
wait # Wait edit_photo to complete, use the wait builtin to keep the script instance active until background jobs complete execution.
play-audio-random /opt/craccken/sound/glitch 2>/dev/null || : # Play random audio in directory

local -a swaylock_appearance=( # Create local array for store swaylock appearance
    # "--no-unlock-indicator"                 # Disable the unlock indicator.
    "--image ${temporary_file}"             # Display the given image, optionally only on the given output.
    # "--show-keyboard-layout"                # Display the current xkb layout while typing.
    # "--hide-keyboard-layout"                # Force hiding the current xkb layout while typing, even if more than one layout is configured or the show-keyboard-layout option is set.
    # "--disable-caps-lock-text"              # Disable the caps lock text.
    "--indicator-caps-lock"                 # Show the current caps lock state also on the indicator
    "--scaling=fill"                        # Image scaling mode: stretch, fill, fit, center, tile, solid_color.
    # "--tiling"                              # Same as --scaling=tile.
    "--color 000000af"                      # Turn the screen into the given color instead of white.
    "--bs-hl-color 080808"                  # Sets the color of backspace highlight segments.
    "--caps-lock-bs-hl-color 080808"        # Sets the color of backspace highlight segments when Caps Lock is active.
    "--caps-lock-key-hl-color f5f5f5"       # Sets the color of the key press highlight segments when Caps Lock is active.
    # "--font=Roboto"                         # Sets the font of the text.
    "--font-size 10"                        # Sets a fixed font size for the indicator text.

    # "--indicator-idle-visible"              # Sets the indicator to show even if idle.
    "--indicator-radius 30"                 # Sets the indicator radius. The default value is 50.
    "--indicator-thickness 2"               # Sets the indicator thickness. The default value is 10.
    "--indicator-x-position 50"             # Sets the horizontal position of the indicator.
    "--indicator-y-position 50"             # Sets the vertical position of the indicator.
    
    "--inside-color 000000"                 # Sets the color of the inside of the indicator.
    "--inside-clear-color 000000"           # Sets the color of the inside of the indicator when cleared.
    "--inside-caps-lock-color 000000"       # Sets the color of the inside of the indicator when Caps Lock is active.
    "--inside-ver-color 000000"             # Sets the color of the inside of the indicator when verifying.
    "--inside-wrong-color 000000"           # Sets the color of the inside of the indicator when invalid.
    "--key-hl-color d5d5d5"                 # Sets the color of the key press highlight segments.
    
    "--layout-bg-color 00000000"            # Sets the background color of the box containing the layout text.
    "--layout-border-color 00000000"        # Sets the color of the border of the box containing the layout text.
    "--layout-text-color 00000000"          # Sets the color of the layout text.
    
    "--line-color 00000000"                 # Sets the color of the line between the inside and ring.
    "--line-clear-color 00000000"           # Sets the color of the line between the inside and ring when cleared.
    "--line-caps-lock-color 00000000"       # Sets the color of the line between the inside and ring when Caps Lock is active.
    "--line-ver-color 030d1100"             # Sets the color of the line between the inside and ring when verifying.
    "--line-wrong-color 14000300"           # Sets the color of the line between the inside and ring when invalid.

    # "--line-uses-inside"                    # Use the inside color for the line between the inside and ring.
    # '--line-uses-ring'                      # Use the ring color for the line between the inside and ring.
    
    "--ring-color 000000"                   # Sets the color of the ring of the indicator when typing or idle.
    "--ring-clear-color 000000"             # Sets the color of the ring of the indicator when cleared.
    "--ring-caps-lock-color 000000"         # Sets the color of the ring of the indicator when Caps Lock is active.
    "--ring-ver-color 36a3d9"               # Sets the color of the ring of the indicator when verifying.
    "--ring-wrong-color cc0022"             # Sets the color of the ring of the indicator when invalid.
    "--separator-color 00000000"            # Sets the color of the lines that separate highlight segments.
    "--text-color d5d5d5"                   # Sets the color of the text.
    "--text-clear-color d5d5d5"             # Sets the color of the text when cleared.
    "--text-caps-lock-color d5d5d5"         # Sets the color of the text when Caps Lock is active.
    "--text-ver-color 36a3d9"               # Sets the color of the text when verifying.
    "--text-wrong-color cc0022"             # Sets the color of the text when invalid.
)
swaylock $(printf "${swaylock_appearance}")
