#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed hyprctl jq # Need install this in order to run

mkdir -p /tmp/$0 # Create temporary directory for this program
local ACTIVE_OPACITY=$(hyprctl getoption decoration:active_opacity -j | jq '.float') # Get option value from hyprland
local INACTIVE_OPACITY=$(hyprctl getoption decoration:inactive_opacity -j | jq '.float') # Get option value from hyprland
local FULLSCREEN_OPACITY=$(hyprctl getoption decoration:fullscreen_opacity -j | jq '.float') # Get option value from hyprland
[[ -f /tmp/$0/saved-value ]] && { # Check if the saved-value file is exist
    hyprctl --batch "\
        keyword decoration:active_opacity $(< /tmp/$0/saved-value | cut -d ' ' -f1);\
        keyword decoration:inactive_opacity $(< /tmp/$0/saved-value | cut -d ' ' -f2);\
        keyword decoration:fullscreen_opacity $(< /tmp/$0/saved-value | cut -d ' ' -f3)" # Restore value from saved-value
    rm -rf /tmp/$0/saved-value # Remove the saved-value file
    eww update "opacity-state=true" 2>/dev/null || :
    return 0 # Exit
}

echo "$ACTIVE_OPACITY $INACTIVE_OPACITY $FULLSCREEN_OPACITY" > /tmp/$0/saved-value # Save gaps into file in temporary directory
hyprctl --batch "keyword decoration:active_opacity ${1:-1}; keyword decoration:inactive_opacity ${2:-1}; keyword decoration:fullscreen_opacity ${1:-1}" # Remove opacity
eww update "opacity-state=false" 2>/dev/null || :
