#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed hyprctl jq # Need install this in order to run

mkdir -p /tmp/$0 # Create temporary directory for this program
local BORDER_SIZE=$(hyprctl getoption general:border_size -j | jq '.int') # Get option value from hyprland
[[ -f /tmp/$0/saved-value ]] && { # Check if the saved-value file is exist
    hyprctl keyword general:border_size "$(< /tmp/$0/saved-value)" # Restore value from saved-value
    rm -rf /tmp/$0/saved-value # Remove the saved-value file
    return 0 # Exit
}

echo "$BORDER_SIZE" > /tmp/$0/saved-value # Save value into file in temporary directory
hyprctl keyword general:border_size 1 # Set the border into 1
