#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed eww # Check if command is installed

[[ "$(eww windows | /usr/bin/grep 'statusbar')" == "*statusbar" ]] && eww close statusbar || eww open statusbar # Toggle the eww statusbar
