#!/bin/env zsh
# vim:ft=sh
if [[ -n "$WAYLAND_DISPLAY" ]] || [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then # Check if running wayland display server
    export ELM_DISPLAY=wl
    export ELM_ENGINE=wayland-egl
    export KITTY_ENABLE_WAYLAND=1                   # Use kitty on native wayland
    export QT_QPA_PLATFORM=wayland-egl              # Run QT apps on native wayland
    export QT_WAYLAND_FORCE_DPI=106                 # To use your monitor's DPI change the value to "physical", instead of the default of 96 DPI
    export QT_WAYLAND_DISABLE_WINDOWDECORATION=1    # Older versions of Qt always show window decorations. This will hide window decorations
    export XDG_SESSION_TYPE=wayland                 # Set display server to wayland
    export GDK_BACKEND=wayland                      # Run GTK apps on native wayland
    export SDL_VIDEODRIVER=wayland                  # Run native game on wayland, It may break most games and other(older) binary applications might not work with wayland SDL video driver.
    export _JAVA_AWT_WM_NONREPARENTING=1            # This will fix some java awt applications not display properly
    export MOZ_ENABLE_WAYLAND=1                     # Experimental wayland support in firefox
    [[ "$(systemd-detect-virt)" == "oracle" ]] && {
        export WLR_NO_HARDWARE_CURSORS=1        # Fix cursor not visible in VM(virtual machine)
    }
fi # End if-else statement
