#!/usr/bin/env zsh
[[ "$XDG_SESSION_TYPE" != "wayland" ]] && return # Check if not running wayland display server then && Stop sourcing this file 

export DISABLE_QT5_COMPAT=0
# export QT_STYLE_OVERRIDE=kvantum
export ELM_DISPLAY=wl                           #
export ELM_ENGINE=wayland_egl                   #
export ECORE_EVAS_ENGINE=wayland_egl            #
# export SDL_VIDEODRIVER=wayland                  # Run native game on wayland, It may break most games and other(older) binary applications might not work with wayland SDL video driver.
export SDL_DYNAMIC_API=/usr/lib/libSDL2-2.0.so
# export WLR_NO_HARDWARE_CURSORS=1                # Fix cursor not visible in VM(virtual machine) and NVIDIA
export LIBSEAT_BACKEND=logind
