#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed fzf # Check if command is installed

local label="${1:-}" # Get argument-1 value and store it into variable
shift 1 # Remove argument-1 value
local -a fzf_style=( # Create local array for store color configurations
    "--color='fg:#36a3d9'"              # Text color
    "--color='bg:#020a0d'"              # Background color
    "--color='preview-fg:#36a3d9'"      # Preview window text
    "--color='preview-bg:#010304'"      # Preview window background
    "--color='hl:#36a3d9:bold'"         # Highlighted substrings
    "--color='fg+:#36a3d9'"             # Text (current line)
    "--color='bg+:#030d11'"             # Background (current line)
    "--color='gutter:#020a0d'"          # Gutter on the left (default to bg+)
    "--color='hl+:#36a3d9:bold:italic'" # Highlighted substrings (current line)
    "--color='query:#36a3d9'"           # Query string
    "--color='disabled:#011b22'"        # Query string when search is disabled
    "--color='info:#023c4b'"            # Info line (match counters)
    "--color='separator:#36a3d9'"       # Horizontal separator on info line (match counters)
    "--color='border:#36a3d9'"          # Border arround the window
    "--color='label:#36a3d9'"           # Border label (--border-label and --preview-label)
    "--color='prompt:#06b8e5'"          # Prompt search
    "--color='pointer:#024455'"         # Pointer to the current line
    "--color='marker:#024c5e:italic'"   # Multi-select marker
    "--color='header:#023c4b'"          # Header text
    "--color='spinner:#0598bd'"         # Streaming input indicator
)
FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS ${fzf_style[@]} --preview-window '0%' --margin '0%'" fzf --height=100% --no-multi --border-label="${label}" "$@" --preview="killall -q paplay; paplay /opt/craccken/sound/move/kpcrgsigf098q2v5gelb.wav 2>/dev/null" 
