#!/usr/bin/env zsh
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                  COMPONENT                                   │
# ╰──────────────────────────────────────────────────────────────────────────────╯
autoload git-current-branch
local -A RESET # Declare local associative array (dictionary)
RESET[BG]="%K{reset}"
RESET[FG]="%F{reset}"
RESET[ALL]="${RESET[BG]}${RESET[FG]}"
local PROMPT_COMPONENT_1="%K{#08090d}%F{%(#.#36a3d9.#242c3d)}▏%F{#242c3d}%n ◈ %m %F{#F5f5f5}${RESET[ALL]}"
local PROMPT_COMPONENT_2="%K{#030d11}%F{#36a3d9}  $(git-current-branch) %~ ${RESET[ALL]}"
local PROMPT_COMPONENT_3="%(1j.%F{#36a3d9}%K{#030d11}  %j ${RESET[ALL]} .)"
local PROMPT_COMPONENT_4="%(?..%F{#cc0022}%K{#140003} 󱎘 %? ${RESET[ALL]} )"
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                    SETUP                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
export RPROMPT2="%F{#00241b}%F{#00c897}%K{#00241b} %^  %L  %! " # Right PROMPT2
export PROMPT2="%K{#00241b}%F{#00c897} %U%y%u  %_ %F{#00241b}${RESET[BG]}${RESET[ALL]} " # PROMPT2 is used to continuation in interactive prompt
export PROMPT4="%K{#20040d}%F{#ba174e} %x  %N %I  %e %_%F{#20040d}${RESET[BG]}${RESET[ALL]} " # The PROMP4/PS4 shell variable defines the prompt that gets displayed, when you execute a shell script in debug mode(setopt xtrace).
export PROMPT_ZSH="${PROMPT_COMPONENT_3}${PROMPT_COMPONENT_4}${PROMPT_COMPONENT_2} ${PROMPT_COMPONENT_1}"
