#!/usr/bin/env zsh
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                  COMPONENT                                   │
# ╰──────────────────────────────────────────────────────────────────────────────╯
autoload git-current-branch
local -A RESET # Declare local associative array (dictionary)
RESET[BG]="%K{reset}"
RESET[FG]="%F{reset}"
RESET[ALL]="${RESET[BG]}${RESET[FG]}"
local PROMPT_COMPONENT_1="%F{%(#.#d70806.#141414)}▎%K{#F5F5F5}%F{#000000} %n ◈ %m %F{#F5f5f5}${RESET[BG]}%K{%(?..#290000)}%F{%(?.#141414.#520000)}┃"
local PROMPT_COMPONENT_2="%K{#F5F5F5}%F{#000000}$(git-current-branch) %~%(1j.%F{#000000} . )${RESET[BG]}%F{#F5F5F5}${RESET[ALL]}"
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                    SETUP                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
export RPROMPT2="%F{#00241b}%F{#00c897}%K{#00241b} %^  %L  %! " # Right PROMPT2
export PROMPT2="%K{#00241b}%F{#00c897} %U%y%u  %_ %F{#00241b}${RESET[BG]}${RESET[ALL]} " # PROMPT2 is used to continuation in interactive prompt
export PROMPT4="%K{#20040d}%F{#ba174e} %x  %N %I  %e %_%F{#20040d}${RESET[BG]}${RESET[ALL]} " # The PROMP4/PS4 shell variable defines the prompt that gets displayed, when you execute a shell script in debug mode(setopt xtrace).
export PROMPT_ZSH="${PROMPT_COMPONENT_1}${PROMPT_COMPONENT_2}"
export NO_RPROMPT=1
