#!/usr/bin/env zsh
#  ██╗   ██╗███████╗███████╗██████╗        █████╗ ██╗     ██╗ █████╗ ███████╗
#  ██║   ██║██╔════╝██╔════╝██╔══██╗      ██╔══██╗██║     ██║██╔══██╗██╔════╝
#  ██║   ██║███████╗█████╗  ██████╔╝█████╗███████║██║     ██║███████║███████╗
#  ██║   ██║╚════██║██╔══╝  ██╔══██╗╚════╝██╔══██║██║     ██║██╔══██║╚════██║
#  ╚██████╔╝███████║███████╗██║  ██║      ██║  ██║███████╗██║██║  ██║███████║
#   ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝      ╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═╝╚══════╝
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │        THIS FILE CONTAIN ALL USER ALIASES, SO ADD YOUR ALIAS HERE!!!         │
# ╰──────────────────────────────────────────────────────────────────────────────╯
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │         NOTE: Do not forget to run zinit-update after editing alias          │
# ╰──────────────────────────────────────────────────────────────────────────────╯
alias l='ls --git-ignore'
alias lx='ls -X'
alias la='ls --all'
alias lt='ls --tree'
alias ll='ls -lhH --accessed --created'
alias :q='exit'
alias lla='ls -lhaH --accessed --created'
alias -- -='cd -'
alias bloated_file='find $PWD -xdev -type f -size +1000M 2>/dev/null'
alias reload_zsh='source /etc/zsh/zshrc'
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                'CLEAR' alias                                 │
# ╰──────────────────────────────────────────────────────────────────────────────╯
alias clear_zsh_history='speak "Clearing;shell history.";rm -v ~/.zsh_history'
alias clear_nvim_history='speak "Clearing;neovim history.";rm -v ~/.local/share/nvim/shada/*'
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                           'OPEN WITH':suffix-alias                           │
# ╰──────────────────────────────────────────────────────────────────────────────╯
alias -s jpg='imv'
alias -s jpeg='imv'
alias -s png='imv'
alias -s svg='imv'
alias -s mkv='mpv'
alias -s mp4='mpv'
alias -s mp3='mpv'
alias -s txt='nvim'
alias -s py='python3'
alias -s log='less +F -MN'
alias -s html='xdg-open'
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                'GLOBAL' alias                                │
# ╰──────────────────────────────────────────────────────────────────────────────╯
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g void='/dev/null'
alias -g leed='| less'
alias -g logging='| ts'
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                   Some aliases from lol plugin ohmyzsh --                    │
# │          https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/lol          │
# ╰──────────────────────────────────────────────────────────────────────────────╯
alias rtfm='man'
alias castlee='curl -s http://artscene.textfiles.com/vt100/castle.vt | pv -q -L 9600'
alias rtfm-zsh='run-help'
alias icanhas='mkdir'
alias gimmeh='touch'
alias dowant='cp -v'
alias donotwant='sudo rm -rfv'
alias gtfo='mv'
alias nowai='chmod'
alias pwned='ssh'
alias byes='sudo shutdown now'
alias cya='sudo reboot'
alias nomz='ps aux'
alias nomnom='killall'
alias rulz='git push'
alias bringz='git pull'
alias hackzor='git init'
alias letcat='git checkout'
alias oanward='git commit -m'
alias yolo='git commit -m "$(curl -s http://whatthecommit.com/index.txt)"'
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                    OTHER                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
alias mountc='mount | column -t'
alias fix-broken-terminal='reset'
alias ascii-table='man ascii'
alias stopwatch='time ( read )'
