#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed hyprctl acpi # Need install this in order to run

mkdir -p /tmp/$0 # Create temporary directory for this program
local WARNING_LEVEL=40 # Declare variable for storing warning level of battery percentage
local lock_file="/tmp/$0/lock-file" # Declare variable for storing the path of lock-file

_toggle_all() {
    toggle-blur
    toggle-dim
    toggle-opacity
    toggle-shadow
    toggle-rounding
    toggle-border
    toggle-animation
}

rm -f ${lock_file} || : # Remove the old lock-file
while :; do # Create infinite-loop
    sleep 20 # Delay interval of the loop
    local battery_status=$(acpi -b | /usr/bin/grep -c "Discharging") # Get battery charge status
    local battery_percentage=$(acpi -b | /usr/bin/grep -P -o "[0-9]+(?=%)") # Get battery percentage and store it into variable
    if [[ ${battery_percentage} -le $WARNING_LEVEL ]] && [[ "${battery_status}" -eq 1 ]] && [[ ! -f "${lock_file}" ]]; then # Check if battery percentage below of WARNING_LEVEL & lock-file did not exist then:
        dunstify --appname="$0" "$0" "Warning your battery low. Please charge your battery!" --urgency critical # Notification
        _toggle_all # Call toggle functions
        hyprctl keyword misc:vfr false # Battery save mode
        touch ${lock_file} # Create lock-file, so the above code for battery-saving did not run every loop
    elif [[ ${battery_percentage} -gt $WARNING_LEVEL ]] && [[ -f "${lock_file}" ]]; then # Check if batter percentage greater of WARNING_LEVEL & lock-file exist then:
        _toggle_all # Call toggle functions
        hyprctl keyword misc:vfr true
        rm -f ${lock_file} || : # Remove the old lock-file
    fi # End if-else statement
done # End while-loop statement
