#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal; set -o pipefail

if [[ -z "$1" ]]; then # Check if argument is empty string
    send_return EINVAL || return $? # Exit with error exit-code
fi # End if-else statement
