#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal; set -o pipefail

if [[ $EUID -eq 0 ]]; then # Check root-user
    send_return EACCES || return $? # Exit with error exit-code
fi # End if-else statement
