#!/usr/bin/env bash
# ISO Specific Variables, READ CAREFULLY FOR YOUR DISTRO
ISO_HOST="Craccken"             # ISO Host Name
ISO_USER="user"           		# Live user account
VERSION="Craccken Installer"    # Installer Name / Version

# This should not need to be changed
ANSWER="/tmp/craccken-installer_answer" # Create a temporary file to store menu selections

# Installation
KEYMAP="us"          					# Virtual console keymap, Default is "us"
XKBMAP="us"      	    				# X11 keyboard layout, Default is "us"

# Architecture
ARCHI=$(uname -m)     					# Display whether 32 or 64 bit system
ROOT_PART=""          					# ROOT partition
UEFI_PART=""							# UEFI partition
UEFI_MOUNT=""         					# UEFI mountpoint
INST_DEV=""           					# Device where system has been installed
HIGHLIGHT=0           					# Highlight items for Main Menu
HIGHLIGHT_SUB=0	    					# Highlight items for submenus
SUB_MENU=""           					# Submenu to be highlighted

# Installation
MOUNTPOINT="/mnt"       				# Installation
AIROOTIMG=""                			# Root image to install
BYPASS="$MOUNTPOINT/bypass/" 			# Root image mountpoint
MOUNT_OPTS="/tmp/.mnt_opts" 			# Filesystem Mount options
FS_OPTS=""								# FS mount options available
CHK_NUM=16								# Used for FS mount options checklist length

modprobe -q efivarfs # Load a module into the kernel with quiet mode
if [[ -d /sys/firmware/efi/ ]]; then # Check if system is UEFI or BIOS
    [[ -z $(mount | grep /sys/firmware/efi/efivars) ]] && mount -t efivarfs efivarfs /sys/firmware/efi/efivars # Mount efivarfs if it is not already mounted
    SYSTEM="UEFI" # Set variable SYSTEM to UEFI
else
    SYSTEM="BIOS" # Set variable SYSTEM to BIOS
fi # End if-else statement
BACKTITLE="$VERSION - $SYSTEM ($ARCHI)"

run_command_in_mountpoint(){ # Create a function 
    arch-chroot $MOUNTPOINT /bin/bash -c "${1}" # Run shell command to mountpoint
}  

check_for_error(){ # Create a function 
    if [[ $? -eq 1 ]] && [[ $(cat /tmp/.errlog | grep -i "error") != "" ]]; then # If there is an error and then
        dialog --backtitle "$BACKTITLE" --title " $_ErrTitle " --msgbox "$(cat /tmp/.errlog)" 0 0 # Display error-msg from log. 
        echo "" > /tmp/.errlog && main_menu # Clear the log && go back to the main menu (no point in continuing).
    fi # End if-else statement
}

check_mount(){ # Create a function
    [[ -z $(lsblk -o MOUNTPOINT | grep ${MOUNTPOINT}) ]] && dialog --backtitle "$BACKTITLE" --title " $_ErrTitle " --msgbox "$_ErrNoMount" 0 0 && main_menu # Ensure that a partition is mounted && Call main_menu function 
}

check_base(){ # Create a function
    [[ ! -e ${MOUNTPOINT}/etc ]] && dialog --backtitle "$BACKTITLE" --title " $_ErrTitle " --msgbox "$_ErrNoBase" 0 0 && main_menu # Ensure that base of craccken has been installed
}

set_locale(){ # Create a function
    local SET_LOCALE_OPT # Create local variable
    for option in $(cat /etc/locale.gen | grep -v "#  " | sed 's/#//g' | sed 's/ UTF-8//g' | grep .UTF-8); do # Create for-loop with locale array in /etc/locale.gen file
        SET_LOCALE_OPT="${SET_LOCALE_OPT} ${option} -"
    done
    dialog --backtitle "$BACKTITLE" --title " $_ConfBseSysLoc " --menu "$_localeBody" 0 0 12 ${SET_LOCALE_OPT} 2>${ANSWER} || config_base_menu 
    echo "LANG=\"$(read_answer)\"" > ${MOUNTPOINT}/etc/locale.conf
    sed -i "s/#$(read_answer)/$(read_answer)/" ${MOUNTPOINT}/etc/locale.gen
    run_command_in_mountpoint "locale-gen" 1>/dev/null
}

set_timezone(){ # Create a function
    local ZONE SUBZONE
    for i in $(cat /usr/share/zoneinfo/zone.tab | awk '{print $3}' | grep "/" | sed "s/\/.*//g" | sort -ud); do
        ZONE="$ZONE ${i} -"
    done
    dialog --backtitle "$BACKTITLE" --title " $_ConfBseTimeHC " --menu "$_TimeZBody" 0 0 10 ${ZONE} 2>${ANSWER} || config_base_menu
    ZONE=$(read_answer) 
    
    for i in $(cat /usr/share/zoneinfo/zone.tab | awk '{print $3}' | grep "${ZONE}/" | sed "s/${ZONE}\///g" | sort -ud); do
        SUBZONE="$SUBZONE ${i} -"
    done
    dialog --backtitle "$BACKTITLE" --title " $_ConfBseTimeHC " --menu "$_TimeSubZBody" 0 0 11 ${SUBZONE} 2>${ANSWER} || config_base_menu
    SUBZONE=$(read_answer) 

    dialog --backtitle "$BACKTITLE" --title " $_ConfBseTimeHC " --yesno "$_TimeZQ ${ZONE}/${SUBZONE}?" 0 0 
    if [[ $? -eq 0 ]]; then
        run_command_in_mountpoint "ln -sf /usr/share/zoneinfo/${ZONE}/${SUBZONE} /etc/localtime" # Set Zone and Sub-Zone
    else
        config_base_menu
    fi # End if-else statement
}

set_hw_clock(){
    run_command_in_mountpoint "hwclock --systohc --localtime" # Check if answer not empty then run command to set hardware clock
}

generate_fstab(){ # Generate the installed system's FSTAB
    [[ $SYSTEM == "BIOS" ]] && genfstab -U -p ${MOUNTPOINT} > ${MOUNTPOINT}/etc/fstab || genfstab -t PARTUUID -p ${MOUNTPOINT} > ${MOUNTPOINT}/etc/fstab
    [[ -f ${MOUNTPOINT}/swapfile ]] && sed -i "s/\\${MOUNTPOINT}//" ${MOUNTPOINT}/etc/fstab
}

set_hostname(){ # Set the installed system's hostname
    dialog --backtitle "$BACKTITLE" --title " $_ConfBseHost " --inputbox "$_HostNameBody" 0 0 "craccken" 2>${ANSWER} || config_base_menu
    echo "$(read_answer)" > ${MOUNTPOINT}/etc/hostname 2>/tmp/.errlog
    echo -e "#<ip-address>\t<hostname.domain.org>\t<hostname>\n127.0.0.1\tlocalhost.localdomain\tlocalhost\t$(read_answer)\n::1\tlocalhost.localdomain\tlocalhost\t$(read_answer)" > ${MOUNTPOINT}/etc/hosts 
}

create_new_user(){ # Create new user(s) for installed system. First user is created by renaming the live account. All others are brand new.
	dialog --backtitle "$BACKTITLE" --title " $_NUsrTitle " --inputbox "$_NUsrBody" 0 0 "" 2>${ANSWER} || config_base_menu
	USER=$(read_answer)
	while [[ ${#USER} -eq 0 ]] || [[ $USER =~ \ |\' ]] || [[ $USER =~ [^a-z0-9\ ] ]]; do # Loop while user name is blank, has spaces, or has capital letters in it.
		dialog --backtitle "$BACKTITLE" --title " $_NUsrTitle " --inputbox "$_NUsrErrBody" 0 0 "" 2>${ANSWER} || config_base_menu
		USER=$(read_answer)
	done # End while-loop statement

	# Enter password. This step will only be reached where the loop has been skipped or broken.
	dialog --backtitle "$BACKTITLE" --title " $_ConfUsrNew " --clear --insecure --passwordbox "$_PassNUsrBody $USER\n\n" 0 0 2> ${ANSWER} || config_base_menu
	PASSWD=$(read_answer) 
	dialog --backtitle "$BACKTITLE" --title " $_ConfUsrNew " --clear --insecure --passwordbox "$_PassReEntBody" 0 0 2> ${ANSWER} || config_base_menu
	PASSWD2=$(read_answer) 
	while [[ ! "$PASSWD" == "$PASSWD2" ]]; do # loop while passwords entered do not match.
		dialog --backtitle "$BACKTITLE" --title " $_ErrTitle " --msgbox "$_PassErrBody" 0 0
		dialog --backtitle "$BACKTITLE" --title " $_ConfUsrNew " --clear --insecure --passwordbox "$_PassNUsrBody $USER\n\n" 0 0 2> ${ANSWER} || config_base_menu
		PASSWD=$(read_answer) 
		dialog --backtitle "$BACKTITLE" --title " $_ConfUsrNew " --clear --insecure --passwordbox "$_PassReEntBody" 0 0 2> ${ANSWER} || config_base_menu
		PASSWD2=$(read_answer) 
	done
    if [[ -e ${MOUNTPOINT}/home/$ISO_USER ]]; then # If the first (or only) user account, then change the live account
        run_command_in_mountpoint "echo '${ISO_USER}:${PASSWD}' | chpasswd" >/dev/null 2>>/tmp/.errlog
        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/home/$ISO_USER/.gtkrc-2.0 2>/tmp/.errlog # Distro-specific configuration for entered username

        # Convert live account to entered username - group, password, folder, and ownership
        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/etc/group 2>>/tmp/.errlog
        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/etc/gshadow 2>>/tmp/.errlog
        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/etc/passwd 2>>/tmp/.errlog
        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/etc/shadow 2>>/tmp/.errlog
        mv ${MOUNTPOINT}/home/$ISO_USER ${MOUNTPOINT}/home/$USER 2>>/tmp/.errlog
        chown -R $USER:users ${MOUNTPOINT}/home/$USER 2>>/tmp/.errlog
        
        # Change sudoers file to require passwords for sudo commands
        # sed -i '/%wheel ALL=(ALL) ALL/s/^#//' ${MOUNTPOINT}/etc/sudoers 2>>/tmp/.errlog
        # sed -i '/%wheel ALL=(ALL) ALL NOPASSWD: ALL/s/#%wheel ALL=(ALL) ALL NOPASSWD: ALL//' ${MOUNTPOINT}/etc/sudoers 2>>/tmp/.errlog
        # check_for_error
	else
        # If the live account has already been changed, create a new user account
        run_command_in_mountpoint "useradd ${USER} -m -g users -G wheel,storage,power,network,video,audio,lp -s /bin/zsh" 2>/tmp/.errlog   
        run_command_in_mountpoint "echo '${USER}:${PASSWD}' | chpasswd" >/dev/null 2>>/tmp/.errlog  
        # run_command_in_mountpoint "passwd ${USER}" < /tmp/.passwd >/dev/null 2>>/tmp/.errlog  

        # Set up basic configuration files and ownership for new account
        run_command_in_mountpoint "cp -R /etc/skel /home/${USER}" 2>>/tmp/.errlog
        run_command_in_mountpoint "chown -R ${USER}:users /home/${USER}" 2>>/tmp/.errlog

        # Update gtk user directories bookmarks
        run_command_in_mountpoint "rm -f /home/${USER}/.config/gtk-3.0/bookmarks" 2>>/tmp/.errlog
        run_command_in_mountpoint "runuser -l ${USER} -c 'xdg-user-dirs-update'" 2>>/tmp/.errlog
        run_command_in_mountpoint "runuser -l ${USER} -c 'xdg-user-dirs-gtk-update'" 2>>/tmp/.errlog
        check_for_error
    fi

    set_root_password(){ # Create a subfunction
        dialog --backtitle "$BACKTITLE" --title " $_ConfUsrRoot " --clear --insecure --passwordbox "$_PassRtBody" 0 0 2> ${ANSWER} || config_base_menu
        local ROOT_PASSWD=$(read_answer)
        dialog --backtitle "$BACKTITLE" --title " $_ConfUsrRoot " --clear --insecure --passwordbox "$_PassReEntBody" 0 0 2> ${ANSWER} || config_base_menu
        local REPEAT_ROOT_PASSWD=$(read_answer)

        if [[ "$ROOT_PASSWD" == "$REPEAT_ROOT_PASSWD" ]]; then
            run_command_in_mountpoint "echo 'root:${ROOT_PASSWD}' | chpasswd" >/dev/null 2>/tmp/.errlog # Set the installed system's root password
        else
            dialog --backtitle "$BACKTITLE" --title " $_ErrTitle " --msgbox "$_PassErrBody" 0 0
            set_root_password # Call set_root_password function
        fi # End if-else statement
    }
    set_root_password
}

run_mkinitcpio(){ # Create a function
    sed -i 's/archiso archiso_loop_mnt archiso_pxe_common archiso_pxe_nbd archiso_pxe_http archiso_pxe_nfs/autodetect/g' ${MOUNTPOINT}/etc/mkinitcpio.conf 2>/tmp/.errlog # Remove archiso hooks from install
    sed -i 's/keyboard/keyboard fsck/g' ${MOUNTPOINT}/etc/mkinitcpio.conf 2>/tmp/.errlog # Add fsck hook
    run_command_in_mountpoint "mkinitcpio -p linux" 2>>/tmp/.errlog
	check_for_error
}

umount_partitions(){
    swapoff --all
    local MOUNTED=$(mount | grep "${MOUNTPOINT}" | awk '{print $3}' | sort -r)
    for mounted_partition in ${MOUNTED[@]}; do
        umount $mounted_partition
    done # End for-loop statement
}

confirm_mount(){ # Revised to deal with partition sizes now being displayed to the user
    if [[ $(mount | grep $1) ]]; then   
        dialog --backtitle "$BACKTITLE" --title " $_MntStatusTitle " --infobox "$_MntStatusSucc" 0 0
        PARTITIONS=$(echo $PARTITIONS | sed "s~${PARTITION} [0-9]*[G-M]~~" | sed "s~${PARTITION} [0-9]*\.[0-9]*[G-M]~~" | sed s~${PARTITION}$' -'~~)
        NUMBER_PARTITIONS=$(( NUMBER_PARTITIONS - 1 ))
    else
        dialog --backtitle "$BACKTITLE" --title " $_MntStatusTitle " --infobox "$_MntStatusFail" 0 0
        prep_menu
    fi # End if-else statement
}

# This function does not assume that the formatted device is the Root installation device as 
# more than one device may be formatted. Root is set in the mount_partitions function.
select_device(){
    DEVICE=""
    devices_list=$(lsblk -lno NAME,SIZE,TYPE | grep 'disk' | awk '{print "/dev/" $1 " " $2}' | sort -u);
    for i in "${devices_list[@]}"; do
        DEVICE="${DEVICE} ${i}"
    done
    dialog --backtitle "$BACKTITLE" --title " $_DevSelTitle " --menu "$_DevSelBody" 0 0 4 ${DEVICE} 2>${ANSWER} || prep_menu
    DEVICE=$(read_answer)
}

find_partitions(){ # Finds all available partitions according to type(s) specified and generates a list of them. This also includes partitions on different devices.
	PARTITIONS=""
	NUMBER_PARTITIONS=0	
	partition_list=$(lsblk -lno NAME,SIZE,TYPE | grep $INCLUDE_PART | sed 's/part$/\/dev\//g' | sed 's/lvm$\|crypt$/\/dev\/mapper\//g' | awk '{print $3$1 " " $2}' | sort -u)
    for i in ${partition_list}; do
        PARTITIONS="${PARTITIONS} ${i}"
        NUMBER_PARTITIONS=$(( NUMBER_PARTITIONS + 1 ))
    done
    NUMBER_PARTITIONS=$(( NUMBER_PARTITIONS / 2 )) # Double-partitions will be counted due to counting sizes, so fix
	case $INCLUDE_PART in
	'part\|lvm\|crypt') # Deal with incorrect partitioning for main mounting function
		if ([[ $SYSTEM == "UEFI" ]] && [[ $NUMBER_PARTITIONS -lt 2 ]]) || ([[ $SYSTEM == "BIOS" ]] && [[ $NUMBER_PARTITIONS -eq 0 ]]); then
			dialog --backtitle "$BACKTITLE" --title " $_ErrTitle " --msgbox "$_PartErrBody" 0 0
			create_partitions
        fi ;;
	'part\|crypt') # Ensure there is at least one partition for LVM 
		if [[ $NUMBER_PARTITIONS -eq 0 ]]; then
			dialog --backtitle "$BACKTITLE" --title " $_ErrTitle " --msgbox "$_LvmPartErrBody" 0 0
			create_partitions
        fi ;;
	'part\|lvm') # Ensure there are at least two partitions for LUKS
		if [[ $NUMBER_PARTITIONS -lt 2 ]]; then
			dialog --backtitle "$BACKTITLE" --title " $_ErrTitle " --msgbox "$_LuksPartErrBody" 0 0
			create_partitions
        fi ;;
	esac
}

create_partitions(){ [[ -n "$DISPLAY" ]] && gparted "${DEVICE}" || parted "${DEVICE}"; }

select_filesystem(){
	fs_opts=""
	CHK_NUM=0
    dialog --backtitle "$BACKTITLE" --title " $_FSTitle " --menu "$_FSBody" 0 0 10 \
        "Skip" "-" \
        "ext4" "mkfs.ext4 -q" \
        "btrfs" "mkfs.btrfs -f" 2>${ANSWER}
	case $(read_answer) in # Read answer from select_filesystem function
		"Skip")
            FILESYSTEM="Skip" ;;
		"btrfs")
            FILESYSTEM="mkfs.btrfs -f"	
            BTRFS_FILESYSTEM=true
			CHK_NUM=16; fs_opts="autodefrag compress=zlib compress=lzo compress=no compress-force=zlib compress-force=lzo discard noacl noatime nodatasum recovery skip_balance space_cache=v2 ssd ssd_spread"
			modprobe btrfs ;;
		"ext4")
            FILESYSTEM="mkfs.ext4 -q"
			CHK_NUM=8; fs_opts="data=journal data=writeback dealloc discard noacl noatime nobarrier nodelalloc" ;;
		*)
            prep_menu ;;
	esac
    if [[ ! $FILESYSTEM == "Skip" ]]; then
        dialog --backtitle "$BACKTITLE" --title " $_FSTitle " --yesno "\n$FILESYSTEM $PARTITION\n\n" 0 0 # Warn about formatting!
        if [[ $? -eq 0 ]]; then
            ${FILESYSTEM} ${PARTITION} >/dev/null 2>/tmp/.errlog
            check_for_error
            if [[ ${BTRFS_FILESYSTEM} ]]; then
                mount ${PARTITION} ${MOUNTPOINT}${MOUNT} 2>>/tmp/.errlog # Normal mounting
                pushd ${MOUNTPOINT}
                btrfs subvolume create @
                btrfs subvolume create @home
                mkdir -p @/{boot/efi,home}
                popd
                umount ${MOUNTPOINT}${MOUNT}
            fi
        else
            select_filesystem
        fi
    fi
}
  
mount_partitions(){
    # This subfunction allows for special mounting options to be applied for relevant fs's.
    # Seperate subfunction for neatness.
    mount_opts() {
        FS_OPTS=""
        echo "" > ${MOUNT_OPTS} # Create temporary file
        for i in ${fs_opts}; do
            FS_OPTS="${FS_OPTS} ${i} - off"
        done
        dialog --backtitle "$BACKTITLE" --title " $(echo $FILESYSTEM | sed "s/.*\.//g" | sed "s/-.*//g") " --checklist "$_btrfsMntBody" 0 0 $CHK_NUM \
        $FS_OPTS 2>${MOUNT_OPTS}
        
        # Now clean up the file
        sed -i 's/ /,/g' ${MOUNT_OPTS}
        sed -i '$s/,$//' ${MOUNT_OPTS}
        if [[ $(cat ${MOUNT_OPTS}) != "" ]]; then # If mount options selected then
            dialog --backtitle "$BACKTITLE" --title " $_MntStatusTitle " --yesno "\n${_btrfsMntConfBody}$(cat ${MOUNT_OPTS})\n" 10 75 # Confirm choice 
            [[ $? -eq 1 ]] && mount_opts
        fi # End if-else statement
    }
    make_swap(){ # Seperate function due to ability to cancel
        dialog --backtitle "$BACKTITLE" --title " $_PrepMntPart " --menu "$_SelSwpBody" 0 0 7 "$_SelSwpNone" $"-" "$_SelSwpFile" $"-" ${PARTITIONS} 2>${ANSWER} || prep_menu  # Ask user to select partition or create swapfile
        if [[ $(read_answer) != "$_SelSwpNone" ]]; then    
            PARTITION=$(read_answer)
            if [[ $PARTITION == "$_SelSwpFile" ]]; then
                total_memory=$(grep MemTotal /proc/meminfo | awk '{print $2/1024}' | sed 's/\..*//')
                dialog --backtitle "$BACKTITLE" --title " $_SelSwpFile " --inputbox "\nM = MB, G = GB\n" 9 30 "${total_memory}M" 2>${ANSWER} || make_swap
                m_or_g=$(read_answer)
                while [[ $(echo ${m_or_g: -1} | grep "M\|G") == "" ]]; do
                    dialog --backtitle "$BACKTITLE" --title " $_SelSwpFile " --msgbox "\n$_SelSwpFile $_ErrTitle: M = MB, G = GB\n\n" 0 0
                    dialog --backtitle "$BACKTITLE" --title " $_SelSwpFile " --inputbox "\nM = MB, G = GB\n" 9 30 "${total_memory}M" 2>${ANSWER} || make_swap
                    m_or_g=$(read_answer)
                done

                fallocate -l ${m_or_g} ${MOUNTPOINT}/swapfile 2>/tmp/.errlog
                chmod 600 ${MOUNTPOINT}/swapfile 2>>/tmp/.errlog
                mkswap ${MOUNTPOINT}/swapfile 2>>/tmp/.errlog
                swapon ${MOUNTPOINT}/swapfile 2>>/tmp/.errlog
                check_for_error
            else # Swap Partition
                if [[ $(lsblk -o FSTYPE "${PARTITION}" | grep -i "swap") != "swap" ]]; then
                    dialog --backtitle "$BACKTITLE" --title " $_PrepMntPart " --yesno "\nmkswap ${PARTITION}\n\n" 0 0 # Warn user if creating a new swap
                    [[ $? -eq 0 ]] && mkswap "${PARTITION}" >/dev/null 2>/tmp/.errlog || mount_partitions
                fi
                swapon  ${PARTITION} >/dev/null 2>>/tmp/.errlog # Whether existing to newly created, activate swap
                check_for_error
                # Since a partition was used, remove that partition from the list
                PARTITIONS=$(echo $PARTITIONS | sed "s~${PARTITION} [0-9]*[G-M]~~" | sed "s~${PARTITION} [0-9]*\.[0-9]*[G-M]~~" | sed s~${PARTITION}$' -'~~)
                NUMBER_PARTITIONS=$(( NUMBER_PARTITIONS - 1 ))
            fi
        fi
    }
    #          ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
    #          ┃                        MOUNTING FUNCTION BEGINS HERE                         ┃
    #          ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
	MOUNT=""
	dialog --backtitle "$BACKTITLE" --title " $_PrepMntPart " --msgbox "$_WarnMount1 'Skip' $_WarnMount2" 0 0 # Warn users that they CAN mount partitions without formatting them!

	# Ensure partitions are unmounted (i.e. where mounted previously), and then list available partitions
	INCLUDE_PART='part\|lvm\|crypt'
    umount_partitions
	find_partitions
	
	# Identify and mount root
	dialog --backtitle "$BACKTITLE" --title " $_PrepMntPart " --menu "\nSelect ROOT Partition. This is where Craccken will be installed." 0 0 7 ${PARTITIONS} 2>${ANSWER} || prep_menu
	PARTITION=$(read_answer)
	select_filesystem # Format with FS (or skip)
    
    [[ $fs_opts != "" ]] && mount_opts # Get mounting options for appropriate filesystems
    if [[ ${BTRFS_FILESYSTEM} ]]; then
        mount -o "$(cat ${MOUNT_OPTS}),subvol=@" ${PARTITION} ${MOUNTPOINT}
        mount -o "$(cat ${MOUNT_OPTS}),subvol=@home" ${PARTITION} ${MOUNTPOINT}/home
    else
        mkdir -p ${MOUNTPOINT}${MOUNT} 2>/tmp/.errlog # Make the mount directory
        if [[ $(cat ${MOUNT_OPTS}) != "" ]]; then # Use special mounting options if selected, else standard mount
            mount -o $(cat ${MOUNT_OPTS}) ${PARTITION} ${MOUNTPOINT}${MOUNT} 2>>/tmp/.errlog # Mount with special options
        else
            mount ${PARTITION} ${MOUNTPOINT}${MOUNT} 2>>/tmp/.errlog # Normal mounting
        fi
    fi
    confirm_mount ${MOUNTPOINT}${MOUNT}
    
	make_swap # Identify and create swap, if applicable
    if [[ $SYSTEM == "UEFI" ]]; then # Extra Step for VFAT UEFI Partition.
        dialog --backtitle "$BACKTITLE" --title " $_PrepMntPart " --menu "\nSelect UEFI Partition. This is a special partition for booting UEFI systems." 0 0 7 ${PARTITIONS} 2>${ANSWER} || prep_menu  
        PARTITION=$(read_answer)
        UEFI_PART=${PARTITION}
        if [[ $(fsck -N $PARTITION | grep fat) ]]; then # If it is already a fat/vfat partition and then
            # DANGEROUS FUNCTION
            # dialog --backtitle "$BACKTITLE" --title " $_PrepMntPart " --yesno "$_FormUefiBody $PARTITION $_FormUefiBody2" 0 0 && mkfs.vfat -F32 ${PARTITION} >/dev/null 2>/tmp/.errlog
            :
        else 
            mkfs.vfat -F32 ${PARTITION} >/dev/null 2>/tmp/.errlog
        fi
        check_for_error
             
        UEFI_MOUNT="/boot/efi"
        mkdir -p ${MOUNTPOINT}${UEFI_MOUNT}
        [[ ${BTRFS_FILESYSTEM} == true ]] && mount ${PARTITION} "${MOUNTPOINT}/@${UEFI_MOUNT}" || mount ${PARTITION} ${MOUNTPOINT}${UEFI_MOUNT}
        confirm_mount ${MOUNTPOINT}${UEFI_MOUNT}
    fi
}	

install_root(){
    if [[ -e /run/archiso/bootmnt/arch/x86_64/airootfs.sfs ]]; then # Change installation method depending on use of img or sfs
        AIROOTIMG="/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
        mkdir -p ${BYPASS} 2>/tmp/.errlog
	    mount ${AIROOTIMG} ${BYPASS} 2>>/tmp/.errlog
        counter=$(find ${BYPASS} | wc -l)
        rsync -av --no-i-r ${BYPASS} ${MOUNTPOINT}/ 2>/tmp/.errlog | pv -len --size "${counter}" --interval 1.0 2>&1 >/dev/null | dialog --backtitle "$BACKTITLE" --title "$VERSION - $SYSTEM ($ARCHI)" --gauge "\n" 10 75
	    umount -l ${BYPASS}
    else
        AIROOTIMG="/run/archiso/airootfs/"
        counter=$(find /run/archiso/airootfs/ | wc -l) # set the counter for pv data
	    # give rsync a progress bar as we install using pv and dialog
        rsync -av --no-i-r ${AIROOTIMG} ${MOUNTPOINT}/ 2>/tmp/.errlog | pv -len --size "${counter}" --interval 1.0 2>&1 >/dev/null | dialog --backtitle "$BACKTITLE" --title "$VERSION - $SYSTEM ($ARCHI)" --gauge "\n" 10 75
    fi
    # Keyboard config for vc and x11
    echo -e "Section "\"InputClass"\"\nIdentifier "\"system-keyboard"\"\nMatchIsKeyboard "\"on"\"\nOption "\"XkbLayout"\" "\"${XKBMAP:-us}"\"\nEndSection" > /tmp/01-keyboard-layout.conf
    [[ -e /tmp/01-keyboard-layout.conf ]] && cp -f /tmp/01-keyboard-layout.conf ${MOUNTPOINT}/etc/X11/xorg.conf.d/$(ls ${MOUNTPOINT}/etc/X11/xorg.conf.d/ | grep "keyboard") 2>>/tmp/.errlog
    if [[ -e /run/archiso/bootmnt/arch/boot/${ARCHI}/vmlinuz-linux ]]; then # set up kernel for mkiniticpio
	    cp /run/archiso/bootmnt/arch/boot/${ARCHI}/vmlinuz-linux ${MOUNTPOINT}/boot/vmlinuz-linux
    else
        cp /usr/lib/modules/$(uname -r)/vmlinuz ${MOUNTPOINT}/boot/vmlinuz-linux
    fi
    cp /etc/pacman.d/mirrorlist ${MOUNTPOINT}/etc/pacman.d/mirrorlist 2>>/tmp/.errlog # copy over new mirrorlist
    /bin/bash -c /opt/craccken-installer/post_install.sh &>>/tmp/.scriptlog
    run_command_in_mountpoint "/bin/bash -c /opt/craccken-installer/chrooted_post_install.sh" &>>/tmp/.scriptlog
    cp /tmp/.scriptlog ${MOUNTPOINT}/var/log/installer_ps_log 2>>/tmp/.errlog
    # Clean up installation
    rm -rf ${MOUNTPOINT}/vomi 2>>/tmp/.errlog
    rm -rf ${BYPASS} 2>>/tmp/.errlog
    rm -rf ${MOUNTPOINT}/source 2>>/tmp/.errlog
    rm -rf ${MOUNTPOINT}/src 2>>/tmp/.errlog
}

install_bootloader(){ # Install Bootloader
    check_mount # Call functions
    run_command_in_mountpoint "PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/core_perl" 2>/tmp/.errlog # Set the default PATH variable
    check_for_error
    
    if [[ $SYSTEM == "BIOS" ]]; then
        select_device
        dialog --backtitle "$BACKTITLE" --title " Grub-install " --infobox "\nPlease wait...\n\n" 0 0
        run_command_in_mountpoint "grub-install --target=i386-pc --recheck $DEVICE" 2>/tmp/.errlog
        run_command_in_mountpoint "grub-mkconfig -o /boot/grub/grub.cfg" 2>>/tmp/.errlog
        check_for_error
        return # Close this functions process
    fi # End if else statement
    
    [[ -z $(mount | grep /sys/firmware/efi/efivars) ]] && mount -t efivarfs efivarfs /sys/firmware/efi/efivars # Ensure again that efivarfs is mounted
    dialog --backtitle "$BACKTITLE" --title " Grub-install " --infobox "\nPlease wait...\n\n" 0 0
    run_command_in_mountpoint "grub-install --target=x86_64-efi --efi-directory=${UEFI_MOUNT} --bootloader-id=CRACCKEN --recheck" 2>/tmp/.errlog
    run_command_in_mountpoint "grub-mkconfig -o /boot/grub/grub.cfg" 2>>/tmp/.errlog # Generate config file
    check_for_error
    dialog --backtitle "$BACKTITLE" --title " $_InstUefiBtTitle " --yesno "$_SetBootDefBody ${UEFI_MOUNT}/EFI/boot $_SetBootDefBody2" 0 0 # Ask if user wishes to set Grub as the default bootloader and act accordingly
    if [[ $? -eq 0 ]]; then
        run_command_in_mountpoint "mkdir ${UEFI_MOUNT}/EFI/boot" 2>/tmp/.errlog
        run_command_in_mountpoint "cp -r ${UEFI_MOUNT}/EFI/craccken_grub/grubx64.efi ${UEFI_MOUNT}/EFI/boot/bootx64.efi" 2>>/tmp/.errlog
        check_for_error
        dialog --backtitle "$BACKTITLE" --title " $_InstUefiBtTitle " --infobox "\nGrub $_SetDefDoneBody" 0 0
    fi
}

prep_menu(){ # Create a function
    clear # Clear terminal screen
    local prep_menu_answer=$(gum choose --selected="${prep_menu_answer}" "List devices (optional)" "1. Partition disk" "2. Mount partitions" "Back") # Choose an options and store it into variable
    case "${prep_menu_answer}" in # Read value from prep_menu_answer variable
        "List devices (optional)") 
            lsblk -o NAME,MODEL,TYPE,FSTYPE,SIZE,MOUNTPOINT | /usr/bin/grep "disk\|part\|lvm\|crypt\|NAME\|MODEL\|TYPE\|FSTYPE\|SIZE\|MOUNTPOINT" | gum pager # Show devices / partitions.
            ;;
        "1. Partition disk") 
            umount_partitions
            select_device
            create_partitions ;;
        "2. Mount partitions") 
            mount_partitions ;;        
        *) main_menu ;;
    esac # End switch-case statement
    prep_menu # Call this functions itself
}

install_root_menu(){ # Base Installation
    clear # Clear terminal screen
    local install_root_menu_answer=$(gum choose --selected="${install_root_menu_answer}" "1. Install Base Packages" "2. Install Bootloader" "Back")
    case "${install_root_menu_answer}" in # Read value from install_root_menu_answer variable
        "1. Install Base Packages") install_root && run_mkinitcpio ;;
        "2. Install Bootloader") install_bootloader ;;
        *) main_menu ;;
    esac # End switch-case statement
    install_root_menu # Call this functions itself
}

config_base_menu(){ # Base Configuration
    run_command_in_mountpoint "PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/core_perl" 2>/tmp/.errlog # Set the default PATH variable
    check_for_error
    clear # Clear terminal screen
    echo "Configure Base"
    echo "Basic configuration of the base."
    local config_base_menu_answer=$(gum choose --selected="${config_base_menu_answer}" "1. Generate FSTAB" "2. Set Hostname" "3. Set System Locale" "4. Set Timezone and Clock" "5. Add New User(s)" "Back")
    case "${config_base_menu_answer}" in # Read value from config_base_menu_answer variable
        "1. Generate FSTAB") generate_fstab ;;
        "2. Set Hostname") set_hostname ;;
        "3. Set System Locale") set_locale ;;        
        "4. Set Timezone and Clock") set_timezone && set_hw_clock ;;
        "5. Add New User(s)") create_new_user ;;
        *) main_menu ;;
    esac
    config_base_menu # Call this functions itself
}

edit_configs_menu(){ # Edit configs of installed system
    local FILE # Clear the file variables
    echo "Review Configuration Files"
    echo "Select any file listed below to be reviewed or amended."
    local edit_configs_menu_answer=$(gum choose --selected="${edit_configs_menu_answer}" "1. /etc/locale.conf" "2. /etc/hostname" "3. /etc/hosts" "4. /etc/mkinitcpio.conf" "5. /etc/fstab" "6. /etc/default/grub" "7. /etc/pacman.conf" "Back")
    case "${edit_configs_menu_answer}" in # Read value from edit_configs_menu_answer variable
        "1. /etc/locale.conf")      FILE="${MOUNTPOINT}/etc/locale.conf" ;;
        "2. /etc/hostname")         FILE="${MOUNTPOINT}/etc/hostname" ;;
        "3. /etc/hosts")            FILE="${MOUNTPOINT}/etc/hosts" ;;
        "4. /etc/mkinitcpio.conf")  FILE="${MOUNTPOINT}/etc/mkinitcpio.conf" ;;
        "5. /etc/fstab")            FILE="${MOUNTPOINT}/etc/fstab" ;;
        "6. /etc/default/grub")     FILE="${MOUNTPOINT}/etc/default/grub" ;;
        "7. /etc/pacman.conf")      FILE="${MOUNTPOINT}/etc/pacman.conf" ;;
        *) main_menu ;;
    esac # End switch-case statement
	nvim $FILE
	edit_configs_menu # Call this functions itself
}

main_menu(){ # Create a function
    while :; do # Create infinite-loop with while-loop
        clear # Clear terminal screen
        local main_menu_answer=$(gum choose --selected="${main_menu_answer}" "1. Prepare Installation" "2. Install base" "3. Configure base" "4. Review configuration files" "Done" "Quit")
        case "${main_menu_answer}" in # Read value from main_menu_answer variable
            "1. Prepare Installation")
                prep_menu
                ;;
            "2. Install base")
                check_mount
                install_root_menu
                ;;
            "3. Configure base")
                check_mount
                check_base
                config_base_menu
                ;;
            "4. Review configuration files")
                check_mount
                check_base
                edit_configs_menu
                ;;
            "Done")
                zsh -ic "warn_msg 'Now you need to reboot!'"
                umount_partitions && exit
                ;;
            *)
                ExitHandler # Call function to handle exit
                ;;
        esac # End switch-case statement
    done # End while-loop
}

read_answer(){
    cat $ANSWER
}

ExitHandler(){
    tput smcup && clear # Save current terminal screen to memory && Clear terminal screen
    local width=$(tput cols)    # Get terminal columns <- width
    local height=$(tput lines)  # Get terminal rows <- height
    gum confirm --prompt.padding="$(( height / 2 )) $(( width / 2 - 8 )) 0 $(( width / 2 - 8 ))" || main_menu && umount_partitions && exit
    tput rmcup # Restore terminal screen from memory
}

# Execution
trap ExitHandler SIGINT
zsh -ic "need_root_user" || exit $?
source /opt/craccken-installer/english.trans # Source translation file for installer
# sed -i "s/#en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen && locale-gen &>/dev/null # Generate the chosen locale
> /tmp/.errlog # Clear error log, just in case something is there from a previous use the installer.

main_menu
