#!/usr/bin/env zsh

main(){
    emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset
    need_installed gh

    local release_dir="$(pwd)/release"
    local release_iso=$(find "${release_dir}" -type f -name "*.iso" -printf "%f\n" || :)
    local release_notes="${release_dir}/release-notes.md"
    local release_version=$(echo "${release_iso}" | cut -d '-' -f 2 | cut -d '.' -f 1,2)
    local release_tag="v${release_version}"
    mkdir -p "${release_dir}" # Create release directory
    # ╭──────────────────────────────────────────────────────────────────────────────╮
    # │                                 Create notes                                 │
    # ╰──────────────────────────────────────────────────────────────────────────────╯
    warn_msg "Creating release notes file..."
    touch "${release_notes}"
    /bin/cat > "${release_notes}" << EOF
### ${release_iso}
- Verify **\`sha256sum\`**
\`\`\`
\$ sha256sum -c ${release_iso}.sha256sum
\`\`\`
### Changelog: 
- Type change-logs here

** Full Changelog: [\`here\`](link)
EOF
    nvim "${release_notes}"
    # ╭──────────────────────────────────────────────────────────────────────────────╮
    # │                              Create new release                              │
    # ╰──────────────────────────────────────────────────────────────────────────────╯
    warn_msg "Creating a new release tag: ${release_tag}"
    gh release create "${release_tag}" -F "${release_notes}" --title "$(print -P '%D{%B %Y : Craccken %Y.%m}')"
    rm -rf "${release_notes}"
    # ╭──────────────────────────────────────────────────────────────────────────────╮
    # │                                Upload assets                                 │
    # ╰──────────────────────────────────────────────────────────────────────────────╯
    local asset
    for asset in ./release/*(.); do
        warn_msg "Uploading: ${asset}"
        gh release upload "${release_tag}" --clobber "${asset}"
    done
}
main
