#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed hyprctl # Need install this in order to run

hyprctl --batch "\
    keyword decoration:blur 0;\
    keyword decoration:drop_shadow 0;\
    keyword decoration:dim_inactive 0;\
    keyword decoration:active_opacity 1;\
    keyword decoration:inactive_opacity 1;\
    keyword decoration:fullscreen_opacity 1;\
    keyword decoration:rounding 0;\
    keyword general:border_size 1;\
    keyword animations:enabled 0"
