#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed acpi dunstify # Check if command is installed || exit
need_normal_user # Need normal user to run || exit

local battery # Create local variable
for battery in /sys/class/power_supply/BAT?; do # Create for-loop with battery as value
    local battery_capacity="$(/bin/cat ${battery}/capacity)" # Get info of battery capacity
done # End for-loop statement
DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus" dunstify --appname="$0" "Charging" "${battery_capacity}% of battery charged." # Send-notification
