#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed lsblk # Check if command is installed || exit with error exit-code
must_have_argument $1 # Must have argument-1 passed || exit 

[[ -n "$(lsblk -o MOUNTPOINT | grep $1)" ]] || send_return ENOMEDIUM || return $? # Check if there is available mountpoint || exit
