#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed mpv pkill chronic # Check if command is installed || exit
need_normal_user # Need normal user to run || exit

pkill -f "https://live.musopen.org:8085/streamvbr0" &>/dev/null || chronic mpv "https://live.musopen.org:8085/streamvbr0" &!
