#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed pacman sync # Check if command is installed || exit with error exit-code

warn_msg " Clearing cache..." # Warning message
speak "Clearing cache" || : # Speaking
ask-password # Ask password
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                     USER                                     │
# ╰──────────────────────────────────────────────────────────────────────────────╯
rm -rf $XDG_CACHE_HOME/**/*(.) # Remove cache home directory in the background
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                    SYSTEM                                    │
# ╰──────────────────────────────────────────────────────────────────────────────╯
warn_msg " Clearing memory cache..."; sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches" || send_return EPERM # Clear memory cache
warn_msg " Removing unneeded dependency..."; [[ -n "$(pacman -Qdt)" ]] && {sudo pacman -Rsnu $(pacman -Qdtq) || send_return EPERM;} || warn_msg "No orphans package to remove!"
wait # Wait the background process done
