#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed sync # Check if command is installed || exit with error exit-code

warn_msg " Clearing memory cache..."; sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches" || send_return EPERM # Clear memory cache
