#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed wl-copy # Check if command is installed || exit
must_have_argument $1 # Must have argument-1 || exit

case $1 in # Read argument-1 value
    "path")
        local directory="${2:-.}" # If no argument-2 passed, use current directory
        [[ $directory = /* ]] || directory="$PWD/$directory" # If argument-2 is not an absolute path, prepend $PWD
        print -n "${directory:a}" | wl-copy # Print $directory without newline | copy the absolute path without resolving symlinks || exit with error exit-code
        info_msg " %B${directory:a}%b copied to clipboard." # Info message
        ;;
    "file")
        [[ -f "$2" ]] && /bin/cat $2 | wl-copy # Check if argument-2 is file && copy contain of file
        ;;
esac # End switch-case statement
