#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed find # Check if command is installed || exit with error exit-code

AskPassword # Ask password || exit
sudo find "${1:-/}" \( -name '*.pacnew' -o -name '*.pacsave' -o -name '*.pacorig' \) 2>/dev/null # Output pacman stuff to terminal
ask_msg "Are you sure?"; local answer; read -q answer # Ask confirmation
(( $? == 0 )) && sudo find "${1:-/}" \( -name '*.pacnew' -o -name '*.pacsave' -o -name '*.pacorig' \) -delete 2>/dev/null # If answer is yes && delete pacman stuff
