#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed find # Check if command is installed || exit with error exit-code

sudo find "${1:-/}" \( -name '*.pacnew' -o -name '*.pacsave' -o -name '*.pacorig' \) 2>/dev/null # Output pacman stuff to terminal
