#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset

local stty_original=$(stty --save) # Save current terminal characteristics.
local query=${1:-11} # Store argument-1 into this variable for query input property from the terminal, 11: text background

stty raw -echo min 0 time 0 # Set terminal characteristics to delay the read timeout and the characters minimum for a completed read
printf "\033]${query};?\033\\" # Print the property from the terminal
sleep 0.00000001 # Read needs timeout to capture the property

local answer; read -rs answer # Read the property and store it into variable
answer="${answer#*\;}" # Remove the escape sequence at the beginning

stty "${stty_original}" # Restore back to the original terminal
print -r $answer | sed 's/[^rgb:0-9a-f/]+$//' # Remove escape at the end.
