#!/usr/bin/env zsh 
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset
need_installed swaylock grim paplay || return $? # Check if command installed || exit
need_normal_user || return $? # Need normal user to run || exit

killall -q swaylock grim paplay # Clean up old process
local temporary_file="/tmp/$(generate-random-string 20).jpg" # Create local variable for storing temporary_file name
sleep 0.32 # Delay screenshot
grim "$temporary_file" # Screenshot the whole screen and then output into temporary_file
paplay $(find /opt/craccken/sound/glitch -maxdepth 1 -type f -readable | shuf -n 1) &>/dev/null & # Play glitch sound
edit_photo glitch "$temporary_file" "$temporary_file" & # Edit the output of screenshot with glitch effect and then output it into temporary_file
wait # Wait edit_photo to complete, use the wait builtin to keep the script instance active until background jobs complete execution.

local -a swaylock_options=( # Create local array for store swaylock options
    "--ignore-empty-password"   # When an empty password is provided, do not validate it.
    # "--debug"                   # Enable debugging output.
    # "--show-failed-attempts"    # Show current count of failed authentication attempts.
    "--daemonize"               # Detach from the controlling terminal after locking.
)
local -a swaylock_appearance=( # Create local array for store swaylock appearance
    # "--no-unlock-indicator"                 # Disable the unlock indicator.
    "--image ${temporary_file}"             # Display the given image, optionally only on the given output.
    "--show-keyboard-layout"                # Display the current xkb layout while typing.
    # "--hide-keyboard-layout"                # Force hiding the current xkb layout while typing, even if more than one layout is configured or the show-keyboard-layout option is set.
    "--indicator-caps-lock"                 # Show the current caps lock state also on the indicator
    "--scaling=fill"                        # Image scaling mode: stretch, fill, fit, center, tile, solid_color.
    "--color 00000000"                      # Turn the screen into the given color instead of white.
    "--bs-hl-color 00000000"                # Sets the color of backspace highlight segments.
    "--caps-lock-bs-hl-color 00000000"      # Sets the color of backspace highlight segments when Caps Lock is active.
    "--caps-lock-key-hl-color 7b00ff"       # Sets the color of the key press highlight segments when Caps Lock is active.
    "--font=Zector"                         # Sets the font of the text.
    "--font-size 20"                        # Sets a fixed font size for the indicator text.
    # "--indicator-idle-visible"              # Sets the indicator to show even if idle.
    "--indicator-radius 77"                 # Sets the indicator radius. The default value is 50.
    "--indicator-thickness 5"               # Sets the indicator thickness. The default value is 10.
    # "--indicator-x-position 0"              # Sets the horizontal position of the indicator.
    # "--indicator-y-position 0"              # Sets the vertical position of the indicator.
    "--inside-color 00000000"               # Sets the color of the inside of the indicator.
    "--inside-clear-color 2300479f"         # Sets the color of the inside of the indicator when cleared.
    "--inside-caps-lock-color 00000000"     # Sets the color of the inside of the indicator when Caps Lock is active.
    "--inside-ver-color 0217229f"           # Sets the color of the inside of the indicator when verifying.
    "--inside-wrong-color 4900199f"         # Sets the color of the inside of the indicator when invalid.
    "--key-hl-color 7fcef7"                 # Sets the color of the key press highlight segments.
    "--layout-bg-color 00000000"            # Sets the background color of the box containing the layout text.
    "--layout-border-color 00000000"        # Sets the color of the border of the box containing the layout text.
    "--layout-text-color 00000000"          # Sets the color of the layout text.
    "--line-color 00000000"                 # Sets the color of the line between the inside and ring.
    "--line-clear-color 00000000"           # Sets the color of the line between the inside and ring when cleared.
    "--line-caps-lock-color 00000000"       # Sets the color of the line between the inside and ring when Caps Lock is active.
    "--line-ver-color 00000000"             # Sets the color of the line between the inside and ring when verifying.
    "--line-wrong-color 00000000"           # Sets the color of the line between the inside and ring when invalid.
    "--ring-color 1236359f"                 # Sets the color of the ring of the indicator when typing or idle.
    "--ring-clear-color 7b00ffef"           # Sets the color of the ring of the indicator when cleared.
    "--ring-caps-lock-color 2300479f"       # Sets the color of the ring of the indicator when Caps Lock is active.
    "--ring-ver-color 7fcef7"               # Sets the color of the ring of the indicator when verifying.
    "--ring-wrong-color ff0057ef"           # Sets the color of the ring of the indicator when invalid.
    "--separator-color 00000000"            # Sets the color of the lines that separate highlight segments.
    "--text-color 00000000"                 # Sets the color of the text.
    "--text-clear-color 7b00ffff"           # Sets the color of the text when cleared.
    "--text-caps-lock-color 00000000"       # Sets the color of the text when Caps Lock is active.
    "--text-ver-color 00000000"             # Sets the color of the text when verifying.
    "--text-wrong-color 00000000"           # Sets the color of the text when invalid.
)
swaylock $(printf "${swaylock_appearance}") $(printf "${swaylock_options}")
