#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn

local -a available_options=( 
    /etc/zsh/prompt/*(.) # Get all file in directory /etc/zsh/prompt and store it as list
) 
local option="${1:-$(print -l ${(o)available_options} | chaos_fzf "Choose your prompt")}" # Declare local variable if argument-1 empty then pick option with fzf
[[ -z "$option" ]] && send_return EINVAL # Check if option is empty string && exit
play_audio_random /opt/craccken/sound/click # Play random audio in directory
basename "$option" > ~/.config/.prompt_theme # Get only the tail of the filepath and output it into file
