#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn

# I stole this idea from lukesmith video: https://www.youtube.com/watch?v=8E8sUNHdzG8&list=WL&index=153
man -k . | chaos_fzf "Pick manual page to read in pdf" | awk '{print $1}' | xargs -r man -Tpdf | zathura -
