#!/usr/bin/env zsh
# vim:ft=sh
#          ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#          ┃                       Read manpage in pdf with zathura                       ┃
#          ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed man zathura xargs awk # Need install this in order to run
autoload spectre_fzf # Load fzf menu

# I stole this idea from lukesmith video: https://www.youtube.com/watch?v=8E8sUNHdzG8&list=WL&index=153
man -k . | spectre_fzf "Pick manual page to read in pdf" | awk '{print $1}' | xargs -r man -Tpdf | zathura -
