#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed hyprctl # Need install this in order to run

{
    hyprctl keyword decoration:blur false # Disable blur
    hyprctl keyword decoration:drop_shadow false # Disable shadow
    hyprctl keyword decoration:dim_inactive false # Disable dim
    hyprctl keyword decoration:active_opacity 1 # Disable opacity
    hyprctl keyword decoration:inactive_opacity 1 # Disable opacity
    hyprctl keyword decoration:fullscreen_opacity 1 # Disable opacity
    hyprctl keyword animations:enabled false # Disable animations
} > /dev/null
