#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn

AskPassword # Ask password
sudo reflector --latest 50 --country ${1:-us} --fastest 10 --protocol http,https --age 12 --sort delay --save /etc/pacman.d/mirrorlist
