#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed awk # Check if command is installed || exit with error exit-code

awk '{$1=$1; print}' "${1:-}"
