#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
autoload spectre_fzf

local -A available_options # Declare local associative array
available_options[xinit]="/etc/X11/xinit"
available_options[dunst]="/etc/dunst"
available_options[sddm]="/etc/sddm.conf.d"
available_options[waybar]="/etc/xdg/waybar"
available_options[eww]="$HOME/.config/eww"
available_options[wofi]="$HOME/.config/wofi"
available_options[newsboat]="$HOME/.config/newsboat"
available_options[temporary]="/tmp"
available_options[udev]="/etc/udev"
available_options[temporary]="/tmp"

available_options[home]="$HOME"
available_options[home__config]="$HOME/.config"
available_options[home__pictures]="$HOME/Pictures"
available_options[home__documents]="$HOME/Documents"
available_options[home__downloads]="$HOME/Downloads"
available_options[home__videos]="$HOME/Videos"
available_options[home__music]="$HOME/Music"
available_options[home__screenshots]="$HOME/Pictures/Screenshots"

available_options[log]="/var/log"
available_options[log__nginx]="/var/log/nginx"

available_options[zsh]="/etc/zsh"
available_options[zsh__zshrc]="/etc/zsh/zshrc.d"
available_options[zsh__zprofile]="/etc/zsh/zprofile.d"
available_options[zsh__alias]="/etc/zsh/alias"
available_options[zsh__trap]="/etc/zsh/functions/trap"
available_options[zsh__prompt]="/etc/zsh/prompt"
available_options[zsh__functions]="/etc/zsh/functions"
available_options[zsh__functions_optionals]="/etc/zsh/functions/optionals"
available_options[zsh__functions_libs]="/etc/zsh/functions/libs"
available_options[zsh__functions_hook]="/etc/zsh/functions/hook"
available_options[zsh__plugin-config]="/etc/zsh/configs"

available_options[neovim]="/etc/xdg/nvim"
available_options[neovim__lua]="/etc/xdg/nvim/lua"
available_options[neovim__colors]="/etc/xdg/nvim/colors"
available_options[neovim__autocommand]="/etc/xdg/nvim/plugin/autocmmand"
available_options[neovim__syntax]="/etc/xdg/nvim/syntax"
available_options[neovim__plugin-config]="/etc/xdg/nvim/after/plugin"
available_options[neovim__filetype-config]="/etc/xdg/nvim/ftplugin"

local option="${1:-$(print -l ${(ko)available_options} | spectre_fzf 'Choose your destination')}" # Declare local variable if argument-1 empty then pick available_options keys value and sorted with fzf
[[ -z "${option}" ]] && send_return EINVAL # If option variable is empty && exit
[[ -z "${available_options[$option]}" ]] && send_return EINVAL # If available_options(option) empty value -> (not valid) && exit
play-audio-random /opt/craccken/sound/click || : # Play random audio in directory
blink-led &! # Call function to blink-led effect
speak "Moving, into ${option} directory." || : # Call function from /etc/zsh/functions to translate text to speak
cd "${available_options[$option]}" 2> /dev/null || speak "Cannot teleport into ${option} directory." || : # Moving into available_options(option) value || exit
