#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed rfkill # Check if command is installed

local current_state=$(rfkill -J | jq -r '.rfkilldevices[] | select(.type == "bluetooth") | .soft' | head -1) # Get current status
[[ "$current_state" == "unblocked" ]] && rfkill block bluetooth || rfkill unblock bluetooth # Toggle it with rfkill
eww update "bluetooth-state=$(rfkill -J | jq -r '.rfkilldevices[] | select(.type == "bluetooth") | .soft' | head -1)" 2> /dev/null || :
