#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed wpctl # Check if command is installed

wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
eww update "audio-state=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | rg -i muted >/dev/null; echo $?)" 2> /dev/null || :
