#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed rfkill # Check if command is installed

local current_state=$(rfkill list | sed -n 2p | awk '{print $3}') # Get current status
[[ "$current_state" == "no" ]] && rfkill block all || rfkill unblock all # Toggle it with rfkill
eww update "airplane-mode-state=$(rfkill list | sed -n 2p | awk '{print $3}')" 2>/dev/null || :
