#!/usr/bin/env zsh
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                          Connect/Disconnect openvpn                          │
# │                  Usage: toggle_openvpn yourconfigfile.ovpn                   │
# ╰──────────────────────────────────────────────────────────────────────────────╯
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed killall openvpn # Check if command is installed

ask-password # Ask password
sudo killall -INT -q openvpn && warn_msg "Disconnected" || {sudo openvpn "$1" &>/dev/null &!; warn_msg "Connected!";}
