#!/usr/bin/env zsh
# vim:ft=sh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed nvim # Check if command is installed || exit with error exit-code

nvim -c "help ${1:-usr_02.txt}|only|nnoremap q ZQ"
