#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed curl jq # Check if command is installed
need_internet # Check if there is available connection

local response=$(curl -s 'https://animechan.vercel.app/api/random') # Get request to web api and store it to response variable
local anime=$(echo "${response}" | jq -r '.anime') # Get anime value from response json
local quote=$(echo "${response}" | jq -r '.quote') # Get qoute value from response json
local character=$(echo "${response}" | jq -r '.character') # Get character value from response json

echo "${quote}\n-- ${character} - ${anime}" # Print the qoute
